### PR TITLE
FAQ : downgrade xbox one controller from Windows

### PR DESCRIPTION
**Pull request by schmurtzm**
Add some details to downgrade xbox one 1708 controller from Windows

### CODE REVIEW

**Comment by ndeadly** [comment]
This is unnecessary. The link from Microsoft has all the information needed, including easy shortcuts for doing it under Windows.

> [Check your controller’s firmware](xboxaccessories://firmwareupdate/?legacyDowngrade=true)

> Note: You can also use this link to revert your controller’s firmware on a Windows device. You will need to have the Xbox Accessories app for Windows installed for the Check your controller’s firmware link to work. If you don’t have the app, get it here:

> [Xbox Accessories app](https://aka.ms/xboxaccessoriesupdateapp)

**Comment by ndeadly** [comment]
Hover over the `Check your controller’s firmware` link. That is the url that it links to

**Comment by schmurtzm** [comment]
Wow OK... You're right all the information is here... It's far from obvious !
But I still think that it should be more detailed in the FAQ to avoid to have more questions about it.

**Comment by ndeadly** [comment]
We have a chatbot command in my discord server regarding xbox firmware downgrades. Of all the people who have been pointed to the MS link, I don't think any of them have had further questions regarding how to actually downgrade. Until that happens I consider this something of a non-issue.

While the use of a hyperlink for this command is somewhat unconventional/unintuitive, I think for the average user it's better than encouraging them run "scary" commands posted by a random user on the internet.

**Pull request closed without merging**
